// This file will be auto-generated by: pnpm --filter @dbc/supabase gen-types
// Run `supabase gen types typescript` after setting up the database schema.
// DO NOT edit manually — changes will be overwritten.

export type Database = Record<string, never>;
